export const READ_PRODUCT_REPOSITORY = Symbol('READ_PRODUCT_REPOSITORY');
export const WRITE_PRODUCT_REPOSITORY = Symbol('WRITE_PRODUCT_REPOSITORY');


export const READ_CATEGORY_REPOSITORY = Symbol('READ_CATEGORY_REPOSITORY');
export const WRITE_CATEGORY_REPOSITORY = Symbol('WRITE_CATEGORY_REPOSITORY');